[workspace]
members = [
    "labadoor-matrix",
    "labadoor-gpio",
    "labadoor-telegram",
    "labadoor-csv",
    "labadoor",
    "labadoor-auth",
    "labadoor-common",
    "labadoor-open",
    "labadoor-acl",
    "labadoor-logging",
]
