[package]
name = "labadoor-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
labadoor-csv = { path = "../labadoor-csv", optional = true }

[features]
csv = ["dep:labadoor-csv"]
