[package]
name = "labadoor-csv"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
csv = "1.1.6"
labadoor-acl = { path = "../labadoor-acl" }
labadoor-logging = { path = "../labadoor-logging" }
