[telegram]
trigger = [ "/usr/bin/labadoor", "open" ]
token = ""

[matrix]
trigger = [ "/usr/bin/labadoor", "open" ]
username = ""
password = ""
device_id = ""

[gpio]
device = ""
pin = 1
active_low = false
active_time = 2000

[log]
backends = ["csv"]

[log.csv]
path = "./labadoor-csv"

[auth]
backends = ["csv"]

[auth.csv]
path = "./labadoor-csv"

[open]
log = [ "/usr/bin/labadoor", "log" ]

[open.auth]
labadoor = [ "/usr/bin/labadoor", "auth" ]

[open.hardware]
tolabaki = [ "/usr/bin/labadoor", "gpio" ]

