[telegram]
trigger = [ "/usr/bin/labadoor", "open" ]
token = ""

[matrix]
username = ""
password = ""
device_id = ""

[gpio]
device = ""
pin = 1
active_low = false
active_time = 2000

[auth]
backends = ["csv"]

[open.auth]
labadoor = [ "/usr/bin/labadoor", "auth" ]

[open.hardware]
tolabaki = [ "/usr/bin/labadoor", "gpio" ]

